using AlgoritmosVariados;

Console.WriteLine(Algoritmos.Soma([]));
Console.WriteLine(Algoritmos.Soma([0]));
Console.WriteLine(Algoritmos.Soma([5, 10, 15, -2, 2]));
Console.WriteLine("---");
Console.WriteLine(Algoritmos.TamanhoArray([]));
Console.WriteLine(Algoritmos.TamanhoArray([5, 10, 15, -2, 2]));
Console.WriteLine("---");
Console.WriteLine(Algoritmos.BuscaMaior([]));
Console.WriteLine(Algoritmos.BuscaMaior([42]));
Console.WriteLine(Algoritmos.BuscaMaior([-2]));
Console.WriteLine(Algoritmos.BuscaMaior([5, 10, 15, -2, 2]));
Console.WriteLine("---");
Console.WriteLine(Algoritmos.BuscaMenor([]));
Console.WriteLine(Algoritmos.BuscaMenor([-42]));
Console.WriteLine(Algoritmos.BuscaMenor([42]));
Console.WriteLine(Algoritmos.BuscaMenor([5, 10, 15, -2, 2]));
Console.WriteLine("---");
Console.WriteLine(Algoritmos.BuscaIdxMenor([]));
Console.WriteLine(Algoritmos.BuscaIdxMenor([-42]));
Console.WriteLine(Algoritmos.BuscaIdxMenor([42]));
Console.WriteLine(Algoritmos.BuscaIdxMenor([5, 10, 15, -2, 2]));
Console.WriteLine("---");
foreach (var i in Algoritmos.OrdenacaoPorSelecao([5, 10, 15, -2, 2])) Console.Write(i + " ");
Console.WriteLine();
foreach (var i in Algoritmos.OrdenacaoPorSelecao([7])) Console.Write(i + " ");
Console.WriteLine();
foreach (var i in Algoritmos.OrdenacaoPorSelecao([])) Console.Write(i + " ");
Console.WriteLine();
foreach (var i in Algoritmos.OrdenacaoPorSelecao([-12])) Console.Write(i + " ");
